E57plugin
helix-re/PDAL pull request #1
Opened 2019-03-29 14:04 UTC by nicolas-chaulet

@srikanthreddybethi please take a look and let me know what you think! When ready I'll submit to the main repo. CI will have to figured out with them but at leasts the tests run locally.

2019-04-03 09:49 UTC, srikanthreddybethi requested changes

2019-04-03 09:49 UTC, srikanthreddybethi commented on plugins/e57/io/E57Reader.cpp
> +E57Reader::ChunkReader::ChunkReader(pdal::point_count_t pointOffset, pdal::point_count_t maxPointRead,
why not const for pointOffset  and maxPointRead

2019-04-03 09:49 UTC, srikanthreddybethi commented on plugins/e57/io/E57Reader.cpp
> +		m_dataReader->close();
it can be single line,  looks nice this way
if (m_dataReader)  m_dataReader->close();

2019-04-03 09:49 UTC, srikanthreddybethi commented on plugins/e57/io/E57Reader.cpp
> +void E57Reader::ChunkReader::setPoint(pdal::point_count_t pointIndex, pdal::PointRef point,
formatting  looks bit weird

2019-04-03 09:49 UTC, srikanthreddybethi commented on plugins/e57/io/E57Reader.cpp
> +		m_imf->close();
same single line code

2019-04-03 09:49 UTC, srikanthreddybethi commented on plugins/e57/io/E57Reader.cpp
> +    E57Reader::E57Reader(std::string filename) : Reader(), Streamable(), m_currentPoint(0), m_pointCount(0)
general convention is  member initialisation should be in next line
some thing like this 
E57Reader::E57Reader(std::string filename) 
: Reader(), Streamable(), m_currentPoint(0), m_pointCount(0)

2019-04-03 09:49 UTC, srikanthreddybethi commented on plugins/e57/io/E57Reader.cpp
> +    while (remaining--)
for loop might be better suited here

2019-04-03 09:49 UTC, srikanthreddybethi commented on plugins/e57/io/E57Reader.cpp
> +    void E57Reader::openFile(const std::string &filename)
weird formating

2019-04-03 09:49 UTC, srikanthreddybethi commented on plugins/e57/io/E57Reader.cpp
> +		static const e57::ustring normalsExtension("http://www.libe57.org/E57_NOR_surface_normals.txt");
why static inside a function....?

2019-04-03 09:49 UTC, srikanthreddybethi commented on plugins/e57/io/E57Reader.cpp
> +	m_chunk = std::unique_ptr<ChunkReader>(new ChunkReader(offset,maxRead,m_scans[currentScan],getDimensions()));
make_unique ...?

2019-04-03 09:49 UTC, srikanthreddybethi commented on plugins/e57/io/E57Reader.hpp
> +    ~E57Reader();
since there are smart pointers as members.. you might want to delete copy constructor and assignment operator...

2019-04-03 09:49 UTC, srikanthreddybethi commented on plugins/e57/io/E57Writer.cpp
> +    m_dataWriter = std::unique_ptr<e57::CompressedVectorWriter>(
make_unique ...?

2019-04-03 09:49 UTC, srikanthreddybethi commented on plugins/e57/io/E57Writer.hpp
> +    E57Writer();
might want to consider deleting copy constructor and assignment operator.

2019-04-03 09:49 UTC, srikanthreddybethi commented on plugins/e57/io/Scan.cpp
> +            // 			m_rotation[0][0] = q00 + q11 - q22 - q33;
why do you want to keep these commented lines..?

2019-04-03 09:49 UTC, srikanthreddybethi commented on plugins/e57/io/Utils.cpp
> +    if (pdalDimension == pdal::Dimension::Id::X)
switch instead of many if else..?

2019-04-04 11:11 UTC, nicolas-chaulet commented on plugins/e57/io/E57Reader.cpp
> +E57Reader::ChunkReader::ChunkReader(pdal::point_count_t pointOffset, pdal::point_count_t maxPointRead,
They are passed as value. Changed them to const references

2019-04-04 11:12 UTC, nicolas-chaulet commented on plugins/e57/io/E57Reader.cpp
> +		m_dataReader->close();
They never use single line in the code base, but I'll remove the brackets

2019-04-04 12:46 UTC, nicolas-chaulet commented on plugins/e57/io/E57Reader.cpp
> +	m_chunk = std::unique_ptr<ChunkReader>(new ChunkReader(offset,maxRead,m_scans[currentScan],getDimensions()));
I don't think we can do that in c++11

2019-04-04 12:49 UTC, nicolas-chaulet commented on plugins/e57/io/E57Reader.hpp
> +    ~E57Reader();
Why is this better? Why don't you want to be able to copy those guys?

2019-04-04 13:00 UTC, srikanthreddybethi commented on plugins/e57/io/E57Reader.hpp
> +    ~E57Reader();
Hmm, you cannot just copy unique_pointer as it is. either you need to do deep copy or you have to move it using std::move()
depending on what you want to do you might have to implement your own copy constructor or assignment operator. 

also for a shared_pointer copy does not create a deep copy, but you need to be sure this is the behavior you want. 

it's better not to support copying objects like this unless there is a good reason. if there is a good reason then its better to implement copy constructor and assignment operator.

2019-04-11 13:21 UTC, srikanthreddybethi approved these changes

2019-04-11 16:49 UTC, closed without merging